root:

modelConfig:
  GPT:
    key: 
    api:
  GPT3.5: gpt-3.5-turbo-0125
  GPT4: gpt-4-1106-preview
  Llama3: 
  Llama2Alpaca: models/Alpaca_llama-2-naive-7b-hf
  Llama2Alpaca-dpo: models/llama-2_align_dpo
  Qwen2-vl:
  Llava1.5:
  InstructBLIP:

datasetsConfig:
   winobias:
     dev:
     test:
   winogender:
     dev:
     test:
   GAP:
     dev:
     test:
   BUG:
     dev:
     test:
   BBQ:
     dev:
     test:
   StereoSet:
     dev:
     test:
   UnQover:
     dev:
     test:

promptConfig:
  DRGAPTemplatePath: config/DRGAPTemplate.json
  QueryTemplatePath: config/QueryTemplate.json
